# Generated by Django 2.2.13 on 2022-09-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_remove_person_imagess'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imagess',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
